#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insert_Aabningstid(_Aabningstid instance);
  partial void Update_Aabningstid(_Aabningstid instance);
  partial void Delete_Aabningstid(_Aabningstid instance);
  partial void Insert_Bruger(_Bruger instance);
  partial void Update_Bruger(_Bruger instance);
  partial void Delete_Bruger(_Bruger instance);
  partial void Insert_Forfatter(_Forfatter instance);
  partial void Update_Forfatter(_Forfatter instance);
  partial void Delete_Forfatter(_Forfatter instance);
  partial void Insert_Kontaktoplysninger(_Kontaktoplysninger instance);
  partial void Update_Kontaktoplysninger(_Kontaktoplysninger instance);
  partial void Delete_Kontaktoplysninger(_Kontaktoplysninger instance);
  partial void Insert_Nyhed(_Nyhed instance);
  partial void Update_Nyhed(_Nyhed instance);
  partial void Delete_Nyhed(_Nyhed instance);
  partial void Insert_Nyhedsbrev(_Nyhedsbrev instance);
  partial void Update_Nyhedsbrev(_Nyhedsbrev instance);
  partial void Delete_Nyhedsbrev(_Nyhedsbrev instance);
  partial void Insert_Serie(_Serie instance);
  partial void Update_Serie(_Serie instance);
  partial void Delete_Serie(_Serie instance);
  partial void Insert_Produkt_Billede(_Produkt_Billede instance);
  partial void Update_Produkt_Billede(_Produkt_Billede instance);
  partial void Delete_Produkt_Billede(_Produkt_Billede instance);
  partial void Insert_Billede(_Billede instance);
  partial void Update_Billede(_Billede instance);
  partial void Delete_Billede(_Billede instance);
  partial void Insert_Produkt(_Produkt instance);
  partial void Update_Produkt(_Produkt instance);
  partial void Delete_Produkt(_Produkt instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<_Aabningstid> _Aabningstids
	{
		get
		{
			return this.GetTable<_Aabningstid>();
		}
	}
	
	public System.Data.Linq.Table<_Bruger> _Brugers
	{
		get
		{
			return this.GetTable<_Bruger>();
		}
	}
	
	public System.Data.Linq.Table<_Forfatter> _Forfatters
	{
		get
		{
			return this.GetTable<_Forfatter>();
		}
	}
	
	public System.Data.Linq.Table<_Kontaktoplysninger> _Kontaktoplysningers
	{
		get
		{
			return this.GetTable<_Kontaktoplysninger>();
		}
	}
	
	public System.Data.Linq.Table<_Nyhed> _Nyheds
	{
		get
		{
			return this.GetTable<_Nyhed>();
		}
	}
	
	public System.Data.Linq.Table<_Nyhedsbrev> _Nyhedsbrevs
	{
		get
		{
			return this.GetTable<_Nyhedsbrev>();
		}
	}
	
	public System.Data.Linq.Table<_Serie> _Series
	{
		get
		{
			return this.GetTable<_Serie>();
		}
	}
	
	public System.Data.Linq.Table<_Produkt_Billede> _Produkt_Billedes
	{
		get
		{
			return this.GetTable<_Produkt_Billede>();
		}
	}
	
	public System.Data.Linq.Table<_Billede> _Billedes
	{
		get
		{
			return this.GetTable<_Billede>();
		}
	}
	
	public System.Data.Linq.Table<_Produkt> _Produkts
	{
		get
		{
			return this.GetTable<_Produkt>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aabningstid")]
public partial class _Aabningstid : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _dag;
	
	private string _aaben;
	
	private string _luk;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndagChanging(string value);
    partial void OndagChanged();
    partial void OnaabenChanging(string value);
    partial void OnaabenChanged();
    partial void OnlukChanging(string value);
    partial void OnlukChanged();
    #endregion
	
	public _Aabningstid()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dag", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string dag
	{
		get
		{
			return this._dag;
		}
		set
		{
			if ((this._dag != value))
			{
				this.OndagChanging(value);
				this.SendPropertyChanging();
				this._dag = value;
				this.SendPropertyChanged("dag");
				this.OndagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aaben", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
	public string aaben
	{
		get
		{
			return this._aaben;
		}
		set
		{
			if ((this._aaben != value))
			{
				this.OnaabenChanging(value);
				this.SendPropertyChanging();
				this._aaben = value;
				this.SendPropertyChanged("aaben");
				this.OnaabenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luk", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
	public string luk
	{
		get
		{
			return this._luk;
		}
		set
		{
			if ((this._luk != value))
			{
				this.OnlukChanging(value);
				this.SendPropertyChanging();
				this._luk = value;
				this.SendPropertyChanged("luk");
				this.OnlukChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bruger")]
public partial class _Bruger : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _bruger_id;
	
	private string _brugernavn;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbruger_idChanging(int value);
    partial void Onbruger_idChanged();
    partial void OnbrugernavnChanging(string value);
    partial void OnbrugernavnChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public _Bruger()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bruger_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int bruger_id
	{
		get
		{
			return this._bruger_id;
		}
		set
		{
			if ((this._bruger_id != value))
			{
				this.Onbruger_idChanging(value);
				this.SendPropertyChanging();
				this._bruger_id = value;
				this.SendPropertyChanged("bruger_id");
				this.Onbruger_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brugernavn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string brugernavn
	{
		get
		{
			return this._brugernavn;
		}
		set
		{
			if ((this._brugernavn != value))
			{
				this.OnbrugernavnChanging(value);
				this.SendPropertyChanging();
				this._brugernavn = value;
				this.SendPropertyChanged("brugernavn");
				this.OnbrugernavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Forfatter")]
public partial class _Forfatter : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _forfatter_id;
	
	private string _forfatter_name;
	
	private EntitySet<_Nyhed> @__Nyheds;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onforfatter_idChanging(int value);
    partial void Onforfatter_idChanged();
    partial void Onforfatter_nameChanging(string value);
    partial void Onforfatter_nameChanged();
    #endregion
	
	public _Forfatter()
	{
		this.@__Nyheds = new EntitySet<_Nyhed>(new Action<_Nyhed>(this.attach__Nyheds), new Action<_Nyhed>(this.detach__Nyheds));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forfatter_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int forfatter_id
	{
		get
		{
			return this._forfatter_id;
		}
		set
		{
			if ((this._forfatter_id != value))
			{
				this.Onforfatter_idChanging(value);
				this.SendPropertyChanging();
				this._forfatter_id = value;
				this.SendPropertyChanged("forfatter_id");
				this.Onforfatter_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forfatter_name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string forfatter_name
	{
		get
		{
			return this._forfatter_name;
		}
		set
		{
			if ((this._forfatter_name != value))
			{
				this.Onforfatter_nameChanging(value);
				this.SendPropertyChanging();
				this._forfatter_name = value;
				this.SendPropertyChanged("forfatter_name");
				this.Onforfatter_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Forfatter__Nyhed", Storage="__Nyheds", ThisKey="forfatter_id", OtherKey="fk_forfatter_id")]
	public EntitySet<_Nyhed> _Nyheds
	{
		get
		{
			return this.@__Nyheds;
		}
		set
		{
			this.@__Nyheds.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach__Nyheds(_Nyhed entity)
	{
		this.SendPropertyChanging();
		entity._Forfatter = this;
	}
	
	private void detach__Nyheds(_Nyhed entity)
	{
		this.SendPropertyChanging();
		entity._Forfatter = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kontaktoplysninger")]
public partial class _Kontaktoplysninger : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _navn;
	
	private int _postnr;
	
	private string _byen;
	
	private string _adresse;
	
	private string _telefon;
	
	private string _email;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnavnChanging(string value);
    partial void OnnavnChanged();
    partial void OnpostnrChanging(int value);
    partial void OnpostnrChanged();
    partial void OnbyenChanging(string value);
    partial void OnbyenChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public _Kontaktoplysninger()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_navn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string navn
	{
		get
		{
			return this._navn;
		}
		set
		{
			if ((this._navn != value))
			{
				this.OnnavnChanging(value);
				this.SendPropertyChanging();
				this._navn = value;
				this.SendPropertyChanged("navn");
				this.OnnavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postnr", DbType="Int NOT NULL")]
	public int postnr
	{
		get
		{
			return this._postnr;
		}
		set
		{
			if ((this._postnr != value))
			{
				this.OnpostnrChanging(value);
				this.SendPropertyChanging();
				this._postnr = value;
				this.SendPropertyChanged("postnr");
				this.OnpostnrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_byen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string byen
	{
		get
		{
			return this._byen;
		}
		set
		{
			if ((this._byen != value))
			{
				this.OnbyenChanging(value);
				this.SendPropertyChanging();
				this._byen = value;
				this.SendPropertyChanged("byen");
				this.OnbyenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string adresse
	{
		get
		{
			return this._adresse;
		}
		set
		{
			if ((this._adresse != value))
			{
				this.OnadresseChanging(value);
				this.SendPropertyChanging();
				this._adresse = value;
				this.SendPropertyChanged("adresse");
				this.OnadresseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string telefon
	{
		get
		{
			return this._telefon;
		}
		set
		{
			if ((this._telefon != value))
			{
				this.OntelefonChanging(value);
				this.SendPropertyChanging();
				this._telefon = value;
				this.SendPropertyChanged("telefon");
				this.OntelefonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nyhed")]
public partial class _Nyhed : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _nyhed_id;
	
	private string _overskrift;
	
	private string _tekst;
	
	private System.DateTime _dato;
	
	private int _fk_forfatter_id;
	
	private EntityRef<_Forfatter> @__Forfatter;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnyhed_idChanging(int value);
    partial void Onnyhed_idChanged();
    partial void OnoverskriftChanging(string value);
    partial void OnoverskriftChanged();
    partial void OntekstChanging(string value);
    partial void OntekstChanged();
    partial void OndatoChanging(System.DateTime value);
    partial void OndatoChanged();
    partial void Onfk_forfatter_idChanging(int value);
    partial void Onfk_forfatter_idChanged();
    #endregion
	
	public _Nyhed()
	{
		this.@__Forfatter = default(EntityRef<_Forfatter>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nyhed_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int nyhed_id
	{
		get
		{
			return this._nyhed_id;
		}
		set
		{
			if ((this._nyhed_id != value))
			{
				this.Onnyhed_idChanging(value);
				this.SendPropertyChanging();
				this._nyhed_id = value;
				this.SendPropertyChanged("nyhed_id");
				this.Onnyhed_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overskrift", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string overskrift
	{
		get
		{
			return this._overskrift;
		}
		set
		{
			if ((this._overskrift != value))
			{
				this.OnoverskriftChanging(value);
				this.SendPropertyChanging();
				this._overskrift = value;
				this.SendPropertyChanged("overskrift");
				this.OnoverskriftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string tekst
	{
		get
		{
			return this._tekst;
		}
		set
		{
			if ((this._tekst != value))
			{
				this.OntekstChanging(value);
				this.SendPropertyChanging();
				this._tekst = value;
				this.SendPropertyChanged("tekst");
				this.OntekstChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dato", DbType="DateTime2 NOT NULL")]
	public System.DateTime dato
	{
		get
		{
			return this._dato;
		}
		set
		{
			if ((this._dato != value))
			{
				this.OndatoChanging(value);
				this.SendPropertyChanging();
				this._dato = value;
				this.SendPropertyChanged("dato");
				this.OndatoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_forfatter_id", DbType="Int NOT NULL")]
	public int fk_forfatter_id
	{
		get
		{
			return this._fk_forfatter_id;
		}
		set
		{
			if ((this._fk_forfatter_id != value))
			{
				if (this.@__Forfatter.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_forfatter_idChanging(value);
				this.SendPropertyChanging();
				this._fk_forfatter_id = value;
				this.SendPropertyChanged("fk_forfatter_id");
				this.Onfk_forfatter_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Forfatter__Nyhed", Storage="__Forfatter", ThisKey="fk_forfatter_id", OtherKey="forfatter_id", IsForeignKey=true)]
	public _Forfatter _Forfatter
	{
		get
		{
			return this.@__Forfatter.Entity;
		}
		set
		{
			_Forfatter previousValue = this.@__Forfatter.Entity;
			if (((previousValue != value) 
						|| (this.@__Forfatter.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Forfatter.Entity = null;
					previousValue._Nyheds.Remove(this);
				}
				this.@__Forfatter.Entity = value;
				if ((value != null))
				{
					value._Nyheds.Add(this);
					this._fk_forfatter_id = value.forfatter_id;
				}
				else
				{
					this._fk_forfatter_id = default(int);
				}
				this.SendPropertyChanged("_Forfatter");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nyhedsbrev")]
public partial class _Nyhedsbrev : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _email;
	
	private int _tilmelding;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntilmeldingChanging(int value);
    partial void OntilmeldingChanged();
    #endregion
	
	public _Nyhedsbrev()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tilmelding", DbType="Int NOT NULL")]
	public int tilmelding
	{
		get
		{
			return this._tilmelding;
		}
		set
		{
			if ((this._tilmelding != value))
			{
				this.OntilmeldingChanging(value);
				this.SendPropertyChanging();
				this._tilmelding = value;
				this.SendPropertyChanged("tilmelding");
				this.OntilmeldingChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Serie")]
public partial class _Serie : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _serie_id;
	
	private string _serie_navn;
	
	private EntitySet<_Produkt> @__Produkts;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onserie_idChanging(int value);
    partial void Onserie_idChanged();
    partial void Onserie_navnChanging(string value);
    partial void Onserie_navnChanged();
    #endregion
	
	public _Serie()
	{
		this.@__Produkts = new EntitySet<_Produkt>(new Action<_Produkt>(this.attach__Produkts), new Action<_Produkt>(this.detach__Produkts));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serie_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int serie_id
	{
		get
		{
			return this._serie_id;
		}
		set
		{
			if ((this._serie_id != value))
			{
				this.Onserie_idChanging(value);
				this.SendPropertyChanging();
				this._serie_id = value;
				this.SendPropertyChanged("serie_id");
				this.Onserie_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serie_navn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string serie_navn
	{
		get
		{
			return this._serie_navn;
		}
		set
		{
			if ((this._serie_navn != value))
			{
				this.Onserie_navnChanging(value);
				this.SendPropertyChanging();
				this._serie_navn = value;
				this.SendPropertyChanged("serie_navn");
				this.Onserie_navnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Serie__Produkt", Storage="__Produkts", ThisKey="serie_id", OtherKey="fk_serie_id")]
	public EntitySet<_Produkt> _Produkts
	{
		get
		{
			return this.@__Produkts;
		}
		set
		{
			this.@__Produkts.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Serie = this;
	}
	
	private void detach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Serie = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produkt_Billede")]
public partial class _Produkt_Billede : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _fk_produkt_id;
	
	private int _fk_billede_id;
	
	private int _id;
	
	private EntityRef<_Billede> @__Billede;
	
	private EntityRef<_Produkt> @__Produkt;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfk_produkt_idChanging(int value);
    partial void Onfk_produkt_idChanged();
    partial void Onfk_billede_idChanging(int value);
    partial void Onfk_billede_idChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
	
	public _Produkt_Billede()
	{
		this.@__Billede = default(EntityRef<_Billede>);
		this.@__Produkt = default(EntityRef<_Produkt>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_produkt_id", DbType="Int NOT NULL")]
	public int fk_produkt_id
	{
		get
		{
			return this._fk_produkt_id;
		}
		set
		{
			if ((this._fk_produkt_id != value))
			{
				if (this.@__Produkt.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_produkt_idChanging(value);
				this.SendPropertyChanging();
				this._fk_produkt_id = value;
				this.SendPropertyChanged("fk_produkt_id");
				this.Onfk_produkt_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_billede_id", DbType="Int NOT NULL")]
	public int fk_billede_id
	{
		get
		{
			return this._fk_billede_id;
		}
		set
		{
			if ((this._fk_billede_id != value))
			{
				if (this.@__Billede.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_billede_idChanging(value);
				this.SendPropertyChanging();
				this._fk_billede_id = value;
				this.SendPropertyChanged("fk_billede_id");
				this.Onfk_billede_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Produkt_Billede", Storage="__Billede", ThisKey="fk_billede_id", OtherKey="billlede_id", IsForeignKey=true)]
	public _Billede _Billede
	{
		get
		{
			return this.@__Billede.Entity;
		}
		set
		{
			_Billede previousValue = this.@__Billede.Entity;
			if (((previousValue != value) 
						|| (this.@__Billede.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Billede.Entity = null;
					previousValue._Produkt_Billedes.Remove(this);
				}
				this.@__Billede.Entity = value;
				if ((value != null))
				{
					value._Produkt_Billedes.Add(this);
					this._fk_billede_id = value.billlede_id;
				}
				else
				{
					this._fk_billede_id = default(int);
				}
				this.SendPropertyChanged("_Billede");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Produkt__Produkt_Billede", Storage="__Produkt", ThisKey="fk_produkt_id", OtherKey="id", IsForeignKey=true)]
	public _Produkt _Produkt
	{
		get
		{
			return this.@__Produkt.Entity;
		}
		set
		{
			_Produkt previousValue = this.@__Produkt.Entity;
			if (((previousValue != value) 
						|| (this.@__Produkt.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Produkt.Entity = null;
					previousValue._Produkt_Billedes.Remove(this);
				}
				this.@__Produkt.Entity = value;
				if ((value != null))
				{
					value._Produkt_Billedes.Add(this);
					this._fk_produkt_id = value.id;
				}
				else
				{
					this._fk_produkt_id = default(int);
				}
				this.SendPropertyChanged("_Produkt");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Billede")]
public partial class _Billede : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _billlede_id;
	
	private string _billede_navn;
	
	private string _billede_sti_300_225;
	
	private string _billede_sti_120_90;
	
	private EntitySet<_Produkt_Billede> @__Produkt_Billedes;
	
	private EntitySet<_Produkt> @__Produkts;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbilllede_idChanging(int value);
    partial void Onbilllede_idChanged();
    partial void Onbillede_navnChanging(string value);
    partial void Onbillede_navnChanged();
    partial void Onbillede_sti_300_225Changing(string value);
    partial void Onbillede_sti_300_225Changed();
    partial void Onbillede_sti_120_90Changing(string value);
    partial void Onbillede_sti_120_90Changed();
    #endregion
	
	public _Billede()
	{
		this.@__Produkt_Billedes = new EntitySet<_Produkt_Billede>(new Action<_Produkt_Billede>(this.attach__Produkt_Billedes), new Action<_Produkt_Billede>(this.detach__Produkt_Billedes));
		this.@__Produkts = new EntitySet<_Produkt>(new Action<_Produkt>(this.attach__Produkts), new Action<_Produkt>(this.detach__Produkts));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billlede_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int billlede_id
	{
		get
		{
			return this._billlede_id;
		}
		set
		{
			if ((this._billlede_id != value))
			{
				this.Onbilllede_idChanging(value);
				this.SendPropertyChanging();
				this._billlede_id = value;
				this.SendPropertyChanged("billlede_id");
				this.Onbilllede_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billede_navn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string billede_navn
	{
		get
		{
			return this._billede_navn;
		}
		set
		{
			if ((this._billede_navn != value))
			{
				this.Onbillede_navnChanging(value);
				this.SendPropertyChanging();
				this._billede_navn = value;
				this.SendPropertyChanged("billede_navn");
				this.Onbillede_navnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billede_sti_300_225", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string billede_sti_300_225
	{
		get
		{
			return this._billede_sti_300_225;
		}
		set
		{
			if ((this._billede_sti_300_225 != value))
			{
				this.Onbillede_sti_300_225Changing(value);
				this.SendPropertyChanging();
				this._billede_sti_300_225 = value;
				this.SendPropertyChanged("billede_sti_300_225");
				this.Onbillede_sti_300_225Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billede_sti_120_90", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string billede_sti_120_90
	{
		get
		{
			return this._billede_sti_120_90;
		}
		set
		{
			if ((this._billede_sti_120_90 != value))
			{
				this.Onbillede_sti_120_90Changing(value);
				this.SendPropertyChanging();
				this._billede_sti_120_90 = value;
				this.SendPropertyChanged("billede_sti_120_90");
				this.Onbillede_sti_120_90Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Produkt_Billede", Storage="__Produkt_Billedes", ThisKey="billlede_id", OtherKey="fk_billede_id")]
	public EntitySet<_Produkt_Billede> _Produkt_Billedes
	{
		get
		{
			return this.@__Produkt_Billedes;
		}
		set
		{
			this.@__Produkt_Billedes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Produkt", Storage="__Produkts", ThisKey="billlede_id", OtherKey="fk_primert_billede_id")]
	public EntitySet<_Produkt> _Produkts
	{
		get
		{
			return this.@__Produkts;
		}
		set
		{
			this.@__Produkts.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach__Produkt_Billedes(_Produkt_Billede entity)
	{
		this.SendPropertyChanging();
		entity._Billede = this;
	}
	
	private void detach__Produkt_Billedes(_Produkt_Billede entity)
	{
		this.SendPropertyChanging();
		entity._Billede = null;
	}
	
	private void attach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Billede = this;
	}
	
	private void detach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Billede = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produkt")]
public partial class _Produkt : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _navn;
	
	private int _pris;
	
	private int _varenr;
	
	private int _design_aar;
	
	private string _beskrivelse;
	
	private string _designer;
	
	private int _fk_serie_id;
	
	private System.Nullable<int> _fk_primert_billede_id;
	
	private EntitySet<_Produkt_Billede> @__Produkt_Billedes;
	
	private EntityRef<_Billede> @__Billede;
	
	private EntityRef<_Serie> @__Serie;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnavnChanging(string value);
    partial void OnnavnChanged();
    partial void OnprisChanging(int value);
    partial void OnprisChanged();
    partial void OnvarenrChanging(int value);
    partial void OnvarenrChanged();
    partial void Ondesign_aarChanging(int value);
    partial void Ondesign_aarChanged();
    partial void OnbeskrivelseChanging(string value);
    partial void OnbeskrivelseChanged();
    partial void OndesignerChanging(string value);
    partial void OndesignerChanged();
    partial void Onfk_serie_idChanging(int value);
    partial void Onfk_serie_idChanged();
    partial void Onfk_primert_billede_idChanging(System.Nullable<int> value);
    partial void Onfk_primert_billede_idChanged();
    #endregion
	
	public _Produkt()
	{
		this.@__Produkt_Billedes = new EntitySet<_Produkt_Billede>(new Action<_Produkt_Billede>(this.attach__Produkt_Billedes), new Action<_Produkt_Billede>(this.detach__Produkt_Billedes));
		this.@__Billede = default(EntityRef<_Billede>);
		this.@__Serie = default(EntityRef<_Serie>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_navn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string navn
	{
		get
		{
			return this._navn;
		}
		set
		{
			if ((this._navn != value))
			{
				this.OnnavnChanging(value);
				this.SendPropertyChanging();
				this._navn = value;
				this.SendPropertyChanged("navn");
				this.OnnavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pris", DbType="Int NOT NULL")]
	public int pris
	{
		get
		{
			return this._pris;
		}
		set
		{
			if ((this._pris != value))
			{
				this.OnprisChanging(value);
				this.SendPropertyChanging();
				this._pris = value;
				this.SendPropertyChanged("pris");
				this.OnprisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_varenr", DbType="Int NOT NULL")]
	public int varenr
	{
		get
		{
			return this._varenr;
		}
		set
		{
			if ((this._varenr != value))
			{
				this.OnvarenrChanging(value);
				this.SendPropertyChanging();
				this._varenr = value;
				this.SendPropertyChanged("varenr");
				this.OnvarenrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_design_aar", DbType="Int NOT NULL")]
	public int design_aar
	{
		get
		{
			return this._design_aar;
		}
		set
		{
			if ((this._design_aar != value))
			{
				this.Ondesign_aarChanging(value);
				this.SendPropertyChanging();
				this._design_aar = value;
				this.SendPropertyChanged("design_aar");
				this.Ondesign_aarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beskrivelse", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string beskrivelse
	{
		get
		{
			return this._beskrivelse;
		}
		set
		{
			if ((this._beskrivelse != value))
			{
				this.OnbeskrivelseChanging(value);
				this.SendPropertyChanging();
				this._beskrivelse = value;
				this.SendPropertyChanged("beskrivelse");
				this.OnbeskrivelseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designer", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string designer
	{
		get
		{
			return this._designer;
		}
		set
		{
			if ((this._designer != value))
			{
				this.OndesignerChanging(value);
				this.SendPropertyChanging();
				this._designer = value;
				this.SendPropertyChanged("designer");
				this.OndesignerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_serie_id", DbType="Int NOT NULL")]
	public int fk_serie_id
	{
		get
		{
			return this._fk_serie_id;
		}
		set
		{
			if ((this._fk_serie_id != value))
			{
				if (this.@__Serie.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_serie_idChanging(value);
				this.SendPropertyChanging();
				this._fk_serie_id = value;
				this.SendPropertyChanged("fk_serie_id");
				this.Onfk_serie_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_primert_billede_id", DbType="Int")]
	public System.Nullable<int> fk_primert_billede_id
	{
		get
		{
			return this._fk_primert_billede_id;
		}
		set
		{
			if ((this._fk_primert_billede_id != value))
			{
				if (this.@__Billede.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_primert_billede_idChanging(value);
				this.SendPropertyChanging();
				this._fk_primert_billede_id = value;
				this.SendPropertyChanged("fk_primert_billede_id");
				this.Onfk_primert_billede_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Produkt__Produkt_Billede", Storage="__Produkt_Billedes", ThisKey="id", OtherKey="fk_produkt_id")]
	public EntitySet<_Produkt_Billede> _Produkt_Billedes
	{
		get
		{
			return this.@__Produkt_Billedes;
		}
		set
		{
			this.@__Produkt_Billedes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Produkt", Storage="__Billede", ThisKey="fk_primert_billede_id", OtherKey="billlede_id", IsForeignKey=true)]
	public _Billede _Billede
	{
		get
		{
			return this.@__Billede.Entity;
		}
		set
		{
			_Billede previousValue = this.@__Billede.Entity;
			if (((previousValue != value) 
						|| (this.@__Billede.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Billede.Entity = null;
					previousValue._Produkts.Remove(this);
				}
				this.@__Billede.Entity = value;
				if ((value != null))
				{
					value._Produkts.Add(this);
					this._fk_primert_billede_id = value.billlede_id;
				}
				else
				{
					this._fk_primert_billede_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("_Billede");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Serie__Produkt", Storage="__Serie", ThisKey="fk_serie_id", OtherKey="serie_id", IsForeignKey=true)]
	public _Serie _Serie
	{
		get
		{
			return this.@__Serie.Entity;
		}
		set
		{
			_Serie previousValue = this.@__Serie.Entity;
			if (((previousValue != value) 
						|| (this.@__Serie.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Serie.Entity = null;
					previousValue._Produkts.Remove(this);
				}
				this.@__Serie.Entity = value;
				if ((value != null))
				{
					value._Produkts.Add(this);
					this._fk_serie_id = value.serie_id;
				}
				else
				{
					this._fk_serie_id = default(int);
				}
				this.SendPropertyChanged("_Serie");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach__Produkt_Billedes(_Produkt_Billede entity)
	{
		this.SendPropertyChanging();
		entity._Produkt = this;
	}
	
	private void detach__Produkt_Billedes(_Produkt_Billede entity)
	{
		this.SendPropertyChanging();
		entity._Produkt = null;
	}
}
#pragma warning restore 1591
